@baseUrl = http://34.225.250.142:3000/api/v1

GET {{baseUrl}}/items

###

POST {{baseUrl}}/auth/signup
content-type: application/json

{
    "name": "nguyenkiet",
    "email": "nguyenkiet@gmail.com",
    "password": "nguyenkiet",
    "passwordConfirm": "nguyenkiet"
}

### 

POST {{baseUrl}}/auth/login
content-type: application/json

{
    "email": "nguyenkiet@gmail.com",
    "password": "nguyenkiet",
    "passwordConfirm": "nguyenkiet"
}